# PMReady - Boston University Product Management Club
# Site configuration

title: PMReady
email: pmready@bu.edu
description: >- 
  PMReady is Boston University's premier product management club, 
  helping students develop the skills and network needed to succeed in PM roles.
baseurl: "" # the subpath of your site
url: "https://pmready.github.io" # the base hostname & protocol
github_username: pmready

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Include the _pages directory
include:
  - _pages

# Navigation
navigation:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Board
    url: /board/
  - title: Programs
    url: /programs/
    subitems:
      - title: Workshops
        url: /programs/workshops/
      - title: Events
        url: /programs/events/
      - title: Impact Internship
        url: /programs/impact-internship/
  - title: Sponsors
    url: /sponsors/
  - title: Sign Up
    url: /signup/

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
